[package]
name = "ntpnet_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true

[dependencies]
syn = { version = "1.0.98", features = ["printing"] }
quote = "1.0"
proc-macro2 = "1.0"
